# Generated by Django 4.2.2 on 2023-07-16 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_avatar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Usuarios',
        ),
    ]
